extends: "eslint:recommended"
parserOptions:
 ecmaVersion: 2017
 sourceType: script
env:
 browser: true
 es6: true
rules:
 eqeqeq: warn
 require-jsdoc:
  - warn
  - require:
      FunctionDeclaration: true
      MethodDefinition: true
      ClassDeclaration: true
      ArrowFunctionExpression: true
      FunctionExpression: true
 no-console: off
 no-constant-condition: warn
 no-unreachable: warn
 no-unused-vars: warn
 semi: error
 valid-jsdoc:
  - error
  - requireReturn: false
    requireReturnDescription: false
    requireReturnType: false
